### ISSUE TITLE
suggestion for startup handling

### ISSUE THREAD

**Issue by BlueKingMuch** [lynxthecat/sqm-autorate#9]
Hello! I'm using this script now for a while before I realized that 99% of the time it doesnt work before it has some strange behaviour on my Turris Omnia.

The reason simplified is, that the script (although it is defined per START Value that it starts after the sqm routine) starts earlier then the sqm routine, throwing out RTNETLINK errors and kind of stay in this faulty situation if I don't log in into the router and stop-start it again.

To "repair" this behavior, I added in the script a new function:

`qdisc_stopped()
{
local QDISCNAME
local qdist_status
QDISCNAME=$1
qdisc_status=$(tc qdisc show dev ${QDISCNAME})

case $qdisc_status in 
  *noqueue*)
    return 0
	;;
	*)
	return 1
esac
}`

and in the main running routine of the sqm-autorate, i just added a big if - else that checks if a queue is set (and therefore sqm is running), and this prevents the script from self locking it into a faulty situation just like i had before. it works like a charm, you even can do stuff with your sqm and stop/start it without the need for reboot (for example when you test new settings for your sqm queues).

**Comment by BlueKingMuch** [comment]
Correction:

i misinterpreted the reason for the self lock in a faulty state. It was not sqm itself, but rather my sometime slow initial connection, which leads to the faulty self lock, see sqm-autorate.log:

`x_bytes_path: /sys/class/net/br-lan/statistics/tx_bytes
tx_bytes_path: /sys/class/net/pppoe-wan/statistics/tx_bytes
connect: Network unreachable
connect: Network unreachable
cat: can't open '/sys/class/net/pppoe-wan/statistics/tx_bytes': No such file or directory
                 log_time;       rx_load;       tx_load;  baseline_RTT;           RTT;     delta_RT>
connect: Network unreachable
connect: Network unreachable
(standard_in) 2: syntax error
(standard_in) 1: syntax error
sh: 1: unknown operand
(standard_in) 1: syntax error
cat: can't open '/sys/class/net/pppoe-wan/statistics/tx_bytes': No such file or directory
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
sh: 1: unknown operand
(standard_in) 1: syntax error
sh: 1: unknown operand
(standard_in) 1: syntax error
sh: 1: unknown operand
(standard_in) 1: syntax error
sh: 1: unknown operand
(standard_in) 1: syntax error
sh: 1: unknown operand
(standard_in) 1: syntax error
sh: 1: unknown operand`

**Comment by lynxthecat** [comment]
Hey there @BlueKingMuch! When the script works (I presume you are using the main branch) does it work well? I am still trying to get feedback on the overall operation. Robustness etc. is really a secondary goal at the moment.

In this situation does the script not just output errors for each tick until the interface comes back up and then start working again? 

Definitely game for including checks if it will increase robustness, but we do need to take care it will not eat up too many CPU cycles because ideally the script runs with as short a time duration between ticks as possible.

**Comment by BlueKingMuch** [comment]
Hey @lynxthecat ! thanks for your fast reply.

With above modification, it is now flawlessly working that the script waits for sqm to start because it checks if a queue is added to the link.

Then I had the problem with my router taking too long for the script to establish the connection:
with readlink the dl_if location symlink (in my case it is ul_if, but only because I use some weird settings on my sqm) i can determine if my pppoe-wan (that's my internet connection) is up or down, that i've already integrated in the script. With this i can prevent a faulty state at bootup state when it takes a longer time for my Router to connect through Modem. 

However, for the situation where the Router is booted fully, everything works, but then a disconnect appears (either someone stepped into the cable or I am tinkering with my connection), then the script gets locked into a faulty state and I can't determine why.  I assume there are some variables which get corrupted because the dl_if and ul_if locations for the symlinks and the files which the script uses are disappearing in the event of a disconnect (I suspect the functions) which i still have no workaround for it.

That's the actual state

**Comment by lynxthecat** [comment]
Many thanks for this. 

Have you tried making service and adding in call to restart service in the main SQM script? The problem is presumably when connection disconnects interface goes, which then screws up the variables for subsequent ticks even when interface comes backs up. By adding in call to restart service in the main SQM script (which restarts via hotplug anyway), a disconnection and reconnection will restart SQM, which will also restart this script. 

Make sense?

**Comment by BlueKingMuch** [comment]
@lynxthecat Welcome, i more have to thank you for this because of how this keeps my work (CAD (Catia V5) on remote virtual machine which is streamed to my local machine) being a perfectly smooth, close to local experience.

That's a good input! However, until now with main sqm I only worked with Luci for the settings, so my knowledge is limited how to implement that behaviour.

In my opinion I would also do this as the last resort, it would be better if this script can do it alone for itself (or in the /etc/init.d "governor" script that starts the main script maybe?)

Reason for this: then it would be also available (and more stable) for people which don't like tinkering too much and would like to keep their sqm instaces untouched

**Comment by BlueKingMuch** [comment]
Update: I've managed to "fix" now the issue with being fault-locked if the connection gets down while the script is running.

it really is a super dirty way, but i moved all the functions into the "main" while loop, also modified each function in that way that I added in the start of every function a while loop which checks if connection is up based on the symlink to my ul_if.

Please do not judge, it really looks (and is) disgusting, but with my limited coding knowledge, i can't do better.

Because my Turris has some kind of beefy specs for a router and handle it pretty well it works good for me, I am not sure if this works for everyone.

actual version of your modified by myself script: https://www.toptal.com/developers/hastebin/gocaselifi.bash

**Comment by BlueKingMuch** [comment]
update from the update: this change broke the function itself, with load now it is stuck to the first increment, the base bandwith get's resetted with every tick. I made it useless.

so this dirty way is not useable, maybe I invest time in near future to find out which variables exactly break on disconnect to integrate a "recovery solution" into the functions which break.

**Comment by BlueKingMuch** [comment]
final update: i got the breakage of the script now fixed.

i moved out all functions again from the main while true routine, and modified the functions in that way that I added simply an if-else which checks the Connection. If it is up, it jumps to the function normally, if it is down, it jumps to first a while - loop which waits for the connection to come up again (and if not, repeat a 5s sleep), then if the connection is up again, it runs a exact copy of the function, only that before the first initial variables which are setted on first startup of the script will be done again.

now i've also tested with load, and it works as intended again.

here's the "final" script, i'll not touch it again until the discussion on openwrt.org is over with a new latency logic:
https://www.toptal.com/developers/hastebin/vicuxopute.bash

**Comment by lynxthecat** [comment]
You may like to try the new version in branch 'CAKE-autorate'.
